# Alacritty ACTIVE CONFIG
# See ~/foobar/ [branch: alacritty-conf] for a safe
# environment to edit settings. Copy this conf file
# to the repository to ensure and up to date conf
# file for editing. Ensure you are on the alacritty-donf
# branch

# alt_send_esc = true
# background_opacity = 1.0
# enable_experimental_conpty_backend = false
# ref_test = false
live_config_reload = true

[env]
# TERM = "alacritty"
TERM = "xterm-256color"

[window]
decorations = "None" # Full, None
dynamic_padding = true # From false
dynamic_title = false
startup_mode = "Windowed"
opacity = 1.0

[window.dimensions]
columns = 81 # Columns wide
lines = 47 # Columns high

[window.position]
x = 2387 # x-axis pixels from top
y = 1 # y-axis pixels from right side

[window.padding]
x = 1
y = 1

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 12.0
# use_thin_strokes = true

[font.normal]
family = "Hack"
style = "Bold"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Bold Italic"

[font.offset]
x = 0
y = -2

[font.glyph_offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true
indexed_colors = []
transparent_background_colors = true

[colors.primary]
# background = '#111111' # personal
# foreground = '#abb2bf' # personal
background = '#1E1E2E' # catppuccin
foreground = '#CDD6F4' # catppuccin
dim_foreground = '#CDD6F4' # catppuccin
bright_foreground = '#CDD6F4' # catppuccin

[colors.cursor]
# text =    '#CDD6F4' # personal
# cursor =  '#D9D9D9' # personal
text = "#1E1E2E" # catppuccin
cursor = "#F5E0DC" # catppuccin

[colors.vi_mode_cursor]
text = "#1E1E2E" # catppuccin
cursor = "#B4BEFE" # catppuccin

[colors.search.matches]
foreground = '#1E1E2E'
background = '#A6ADC8'

[colors.search.focused_match]
foreground = '#1E1E2E'
background = '#A6E3A1'

# [colors.search.footer_bar] # footer_bar may be deprecated
# foreground = '#1E1E2E'
# background = '#A6ADC8'

[colors.hints.start]
foreground = '#1E1E2E' # catppuccin
background = '#F9E2AF' # catppuccin

[colors.hints.end]
foreground = '#1E1E2E' # catppuccin
background = '#A6ADC8' # catppuccin

[colors.selection]
text = '#1E1E2E' # catppuccin
background = '#F5E0DC' # catppuccin

[colors.bright]
black =   '#585B70' # catppuccin
red =     '#F38BA8' # catppuccin
green =   '#A6E3A1' # catppuccin
yellow =  '#F9E2AF' # catppuccin
blue =    '#89B4FA' # catppuccin
magenta = '#F5C2E7' # catppuccin
cyan =    '#94E2D5' # catppuccin
white =   '#A6ADC8' # catppuccin
# black =   '#5c6370'
# red =     '#e06c75'
# green =   '#98c379'
# yellow =  '#d19a66'
# blue =    '#61afef'
# magenta = '#c678dd'
# cyan =    '#56b6c2'
# white =   '#ffffff'

[colors.normal]
black =   '#45475A' # catppuccin
red =     '#F38BA8' # catppuccin
green =   '#A6E3A1' # catppuccin
yellow =  '#F9E2AF' # catppuccin
blue =    '#89B4FA' # catppuccin
magenta = '#F5C2E7' # catppuccin
cyan =    '#94E2D5' # catppuccin
white =   '#BAC2DE' # catppuccin
# black =     '#1e2127'
# red =       '#e06c75'
# green =     '#98c379'
# yellow =    '#d19a66'
# blue =      '#61afef'
# magenta =   '#c678dd'
# cyan =      '#56b6c2'
# white =     '#abb2bf'

[colors.dim]
black = "#45475A" # catppuccin
red = "#F38BA8" # catppuccin
green = "#A6E3A1" # catppuccin
yellow = "#F9E2AF" # catppuccin
blue = "#89B4FA" # catppuccin
magenta = "#F5C2E7" # catppuccin
cyan = "#94E2D5" # catppuccin
white = "#BAC2DE" # catppuccin

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

# opacity: 23
# size: 42
# family: 46,54
# colors: 65,98
# bright: 80,88
# normal: 90,98

# Changes

# opacity
# $ opacity [0.n]

# size
# $ sed -i '42s/size\s=\s.*/size = [n]n.n/' ~/.config/alacritty/alacritty.toml

# fonts
# $ ~/bashscripts/alacrifont.sh
